### ISSUE TITLE
Repeated pinning

### ISSUE THREAD

**Issue by tlvince** [greenkeeperio/support#10]
After the initial PR that pins all dependencies is received, if the user then adds a new dependency with `npm i -S [dep]` (saved with a semver range by default), should a subsequent pin PR be sent? Currently, it appears Greenkeeper doesn't check for this. Perhaps `--save-exact` should be recommended?

**Comment by gr2m** [comment]
Good point, thanks for bringing it up, Tom! We'll look into it

**Comment by boennemann** [comment]
We've added support for version ranges just now, which means we can no longer assume that a certain version range was added unintentionally.

Should you decided to only use pin dependencies we will fix this problem by implementing this: https://github.com/greenkeeperio/greenkeeper/issues/30
