### ISSUE TITLE
Ignore pre-releases

### ISSUE THREAD

**Issue by tlvince** [greenkeeperio/support#11]
We just received a [greenkeeper pull request](https://github.com/eHealthAfrica/direct-delivery-dashboard/pull/157) for a package that released an rc. Perhaps these should be ignored by default?

**Comment by tlvince** [comment]
NB, that pull request was rather dubiously auto closed by a bot account. Does/could greenkeeper do this?

**Comment by boennemann** [comment]
We're thinking of a good/better way to handle pre-releases, thanks for the feedback here.

Regarding the auto closing here is the full explanation of what happened:

We rolled out a new feature where we're first waiting for the CI results of versions inside your current version range, and then remove that branch again when tests passed, or open the PR when they failed.
For pull-requests outside of the range we were missing a check in some cases, so the status webhook from github came in, we detected that the branch passed and removed it again, disregarding that there was already a PR for that branch, for good reasons. Deleting the branch of PR also closes that PR.
Once we saw the auto closing of PRs appearing in our logs, we added the missing check, so PRs won't be closed accidentally again.

Sorry for the inconvenience.


Best,
Stephan

**Comment by tlvince** [comment]
No probs. Appreciate the response. Thanks Stephan!

(I'll leave this issue open with regards to pre-releases).

**Comment by boennemann** [comment]
Hey @tlvince,

sorry for taking so long. We're no longer sending PRs for pre-release versions now.

Best,
Stephan

**Comment by tlvince** [comment]
:+1:
