### ISSUE TITLE
Pin new dependencies

### ISSUE THREAD

**Issue by ariporad** [greenkeeperio/support#12]
Hi,

I'm wondering if it's possible for greenkeeper to be even more awesome, and automagically pin any new dependencies. For example, if I `npm install --save super-awesome-package`, and that saves the version to my package.json as `^5.3.8`, I'd like greenkeeper to automagically send a pull request changing that to `5.3.8` (or the latest version).

Is this possible?

Thanks!

**Comment by boennemann** [comment]
Hey Ari,

as Greenkeeper is no longer a service that requires pinning we can't assume that that's what our user want every single time.

Thanks for understanding.

Best,
Stephan
