### ISSUE TITLE
Failing builds due to missing branches

### ISSUE THREAD

**Issue by javiercejudo** [greenkeeperio/support#13]
I am struggling to make sense of some failing builds in repos where I have enabled greenkeeper. See build [84656967](https://travis-ci.org/javiercejudo/linear-presets-area/builds/84656967), following successful [84656887](https://travis-ci.org/javiercejudo/linear-presets-area/builds/84656887). The failing one says `warning: Could not find remote branch greenkeeper-gulp-3.9.0 to clone`.

Weirdly enough, even though [master hasn't failed](https://travis-ci.org/javiercejudo/linear-presets-area/branches), github [reports it as failing](https://github.com/javiercejudo/linear-presets-area/branches).

![selection_016](https://cloud.githubusercontent.com/assets/1095851/10411403/ff9151f8-6faf-11e5-983f-07a5f7936697.png)

Other affected builds in different repos:

[84657004](https://travis-ci.org/javiercejudo/linear-presets-amount-of-substance/builds/84657004)
[84656995](https://travis-ci.org/javiercejudo/linear-presets-amount-of-substance/builds/84656995)
[84656967](https://travis-ci.org/javiercejudo/linear-presets-amount-of-substance/builds/84656967)
[84656970](https://travis-ci.org/javiercejudo/linear-presets-amount-of-substance/builds/84656970)
[84656968](https://travis-ci.org/javiercejudo/linear-presets-amount-of-substance/builds/84656968)

**Comment by boennemann** [comment]
Hey @javiercejudo,

all the failing builds you're linking to are the merge commits. I don't know why these merge commits would require the branch to still exist, but I can't see where this related to Greenkeeper.

Is this something that keeps reappearing, or only appearing if you merge PRs from Greenkeeper?

Best,
Stephan

**Comment by javiercejudo** [comment]
It doesn't seem to be reappearing. Filed it here because the failing builds were initiated automatically since I enabled greenkeeper. Correct me if I'm wrong: when greenkeeper detects an update, a new branch is created on my behalf, which triggers a build, then greenkeeper authors a change on that branch that is committed on my behalf triggering a second build.

In that case, the builds I linked to would be the first build triggered.

**Comment by javiercejudo** [comment]
Hi @boennemann,

If you can confirm what I said above is right, I guess it's possible that Travis might run the builds in reverse order: the one with the greenkeeper change first, which removes the branch when it passes, then the build triggered by the creation of the new branch, which now does not exist!

Incidentally, Github would see that failed build in which the latest commit is the latest one in master as failed, hence master is flagged as failing. Not sure this is what's happening, but it fits the symptoms.

**Comment by boennemann** [comment]
Hey @javiercejudo,

we had another look at this and we were first creating the branch and then pushing a commit to that branch, as you said, which caused all kinds of weird behaviour, due to a lot of Status API hooks being emitted.

We fixed this now, so you should only see one build for the branch, and if we open a PR you'll see a second build.

Best,
Stephan

**Comment by javiercejudo** [comment]
Thanks for following up on this, @boennemann!
