### ISSUE TITLE
Feature request: cumulative updates 

### ISSUE THREAD

**Issue by princed** [greenkeeperio/support#15]
At least for some fast-moving modules.
I **love** greenkeeper, but I'm sort of tired of endless eslint minor updates:

![image](https://cloud.githubusercontent.com/assets/796050/10600822/038f8df2-7716-11e5-94c2-c9282fcaaf08.png)

**Comment by Andersos** [comment]
They no longer require pinned dependencies so if you update to a ^ dependency you should see less updates.

**Comment by princed** [comment]
It kills idea of always-tested explicitly-updated dependencies.

**Comment by boennemann** [comment]
Hey @princed,

thanks for your feedback. As @Andersos mentioned our way to reduce the noise are version ranges.
It's right that these don't give you explicitly updated dependencies, but that doesn't mean they can't be _always-tested_.

We introduced [“Real Time Dependency Break Detection”](https://medium.com/greenkeeper-blog/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77), which means we'll keep creating branches for every single update, but we'll only open a pull request, when that breaks your tests. When it passes we delete the branch again and you won't be bothered.

You can define the level of *noise* per dependency by using either `>=` `^`, `~` or pinning.

Best,
Stephan

**Comment by princed** [comment]
Good news! Thank you, @boennemann!
