### ISSUE TITLE
Failing to sync organization and find slug.

### ISSUE THREAD

**Issue by suitupalex** [greenkeeperio/support#17]
FIrst of all, absolutely love the service. Keep up the good work!

I've previously been successful at enabling Greenkeeper on various repos in all of my public organizations, but my newest one isn't cooperating.

When I do `greenkeeper sync`, my forks show up for @twitch-sm4shbot, but not the upstream repos.

Trying to do `greenkeeper --slug=twitch-sm4shbot/twitch-sm4shbot enable` results in the "couldn't enable  a project with this slug" error.

I successfully enabled it on my personal fork, but that's less than ideal. This might also be related to #4.

**Comment by christophwitzko** [comment]
Hi @suitupalex,

it looks like Greenkeeper has no access to the `twitch-sm4shbot` organization on GitHub.
To grant Greenkeeper access you can run `greenkeeper access` and after that `greenkeeper sync` to resync your repositories.

Have a great day,
Christoph
