### ISSUE TITLE
For consecutive versions, just change the PR.

### ISSUE THREAD

**Issue by ariporad** [greenkeeperio/support#18]
I'm back, I'm sorry.

Here's the not-so-awesome side of greenkeeper that I'm seeing: [http://ariporad.link/1RGEPwe](http://ariporad.link/1RGEPwe). It would be really nice, if when a PR hasn't been merged, and a new version comes out, if the PR was just updated, vs a new one being opened.

Thanks!

**Comment by boennemann** [comment]
Hey Ari,
thanks for the feedback. I'm closing this in favor of https://github.com/greenkeeperio/greenkeeper/issues/62.
I'll post our plans on this there today.

Best,
Stephan
