### ISSUE TITLE
Open does not work on Debian Jessie

### ISSUE THREAD

**Issue by wblankenship** [greenkeeperio/support#2]
It will open two tabs, one with the url `http/` and the other `file:///api.greenkeeper.io/login%3Fid=[REDACTED]`

Proposed solution: migrate to `openurl`.

Example implementation: https://github.com/wblankenship/greenkeeper

**Comment by boennemann** [comment]
Hey @wblankenship,

thanks for reporting this. We've just open sourced the CLI, so if you like you can send us a PR now :)
http://github.com/greenkeeperio/greenkeeper

Best,
Stephan
