### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by hemanth** [greenkeeperio/support#3]
![screen shot 2015-09-26 at 20 02 29](https://cloud.githubusercontent.com/assets/18315/10118026/cc88e982-6489-11e5-82e6-e1c2f8a3387c.png)

**Comment by gr2m** [comment]
Can you please try to change `"repository": "hemanth/node-nmp-whoshiring"` in your package.json to 

```
"repository": {
  "type": "git",
  "url": "https://github.com/hemanth/node-npm-whoshiring.git"
}
```

push it to master, then try to enable again?

**Comment by hemanth** [comment]
Well, `https://` is not mandatory in `package.json`

**Comment by hemanth** [comment]
`$ greenkeeper enable --slug <user>/<repo>` helps?

**Comment by boennemann** [comment]
Hey @hemanth,

we're reading the github-slug from the configured git remote "origin" with npm.im/github-slug. It looks like the fail is also happening in this module. Is there anything odd in your `.git/config` file? 

Best,
Stephan

**Comment by hemanth** [comment]
No, nothing strange in `.git/config`.

**Comment by boennemann** [comment]
I'm closing this in favor of https://github.com/greenkeeperio/greenkeeper/issues/15, as we're migrating all issues over to the source repo.

Best,
Stephan

**Comment by hemanth** [comment]
:+1:
