### ISSUE TITLE
A repo with this slug doesn’t exist on GitHub

### ISSUE THREAD

**Issue by Andersos** [greenkeeperio/support#4]
So looks like there is a bug
```bash
$ greenkeeper enable
🌴  info enable The GitHub slug is: Andersos/eslint-config-andersos
🌴  ERR! enable A repo with this slug doesn’t exist on GitHub
```

It happens with all my repos. Maybe it has something with me having a name that starts with an uppercase letter. Or maybe the repo has to be written a certain way in package.json.

**Comment by christophwitzko** [comment]
Hi @Andersos,

it looks like your repos are not synced with our database.
Can you try to run `greenkeeper sync` in your terminal?

Best,
Christoph

**Comment by hemanth** [comment]
Related to #3

**Comment by Andersos** [comment]
```bash
$ greenkeeper sync
🌴  info sync This might take a while
🌴  ERR! sync Bad Gateway
🌴  ERR! load Woops, this is an unexpected error.
🌴  ERR! load We just started this service, so maybe it's just be too much load for us right now.
🌴  ERR! load Please try again later, while we're busy spinning up more machines for you <3
🌴  ERR! load Oh, and if this keeps reappearing – Please let us know: support@greenkeeper.io
```

**Comment by boennemann** [comment]
There are currently more people experiencing this problem with "enable" on some repos and we're trying to identify the problem here. We'll keep you posted on the progress in this Issue. 

Thanks for your reports everyone.

Best,
Stephan

**Comment by boennemann** [comment]
Alright everyone, this is fixed now. Sorry for the inconvenience, but in an effort to reduce the required GitHub scope we've gone slightly too far. Please run `greenkeeper login --force` once again and then you should be able to enable your repos as expected.

Please report back whether it worked so I can close this issue :)

Best,
Stephan

**Comment by hemanth** [comment]
@boennemann Did a force login and noticed the same :( 

```sh
🌴  ERR! enable hemanth/adventure-runner is already enabled
🌴  ERR! enable If this repo is inside an organization, somebody other than you may have done this
🌴  info enable The GitHub slug is: hemanth/all-builtins
🌴  ERR! enable A repo with this slug doesn’t exist on GitHub
🌴  info enable The GitHub slug is: hemanth/an-async
🌴  ERR! enable A repo with this slug doesn’t exist on GitHub
🌴  info enable The GitHub slug is: hemanth/arey
🌴  ERR! enable A repo with this slug doesn’t exist on GitHub
🌴  info enable The GitHub slug is: hemanth/audio-type
🌴  ERR! enable hemanth/audio-type is already enabled
```

**Comment by christophwitzko** [comment]
Hey @hemanth,

it looks like these three repos are not on Github:
https://api.github.com/repos/hemanth/all-builtins
https://api.github.com/repos/hemanth/an-async
https://api.github.com/repos/hemanth/arey

Probably they are private?

have a nice day,
Christoph

**Comment by hemanth** [comment]
@christophwitzko My bad, thanks!

**Comment by Widdershin** [comment]
This fix worked great for me, thanks to y'all.

https://github.com/cyclejs/cycle-time-travel/pull/23

:smile:

**Comment by tlvince** [comment]
It's also worth noting that your GitHub user requires (at least) write access to the repo, e.g. if you're using a separate CI/bot account.

**Comment by rt2zz** [comment]
I believe this issue persists for repo's which have been renamed. In my case `https://github.com/rt2zz/redux-persist-store` -> `https://github.com/rt2zz/redux-persist`

greenkeeper enable stdout:
```
🌴  info enable The GitHub slug is: rt2zz/redux-persist-store
🌴  ERR! enable Couldn’t find a repo with this slug.
🌴  ERR! enable Either it doesn’t exist on GitHub, it’s a fork, or private.
```

**Comment by hemanth** [comment]
@rt2zz That's more an issue of `github-slug` module than geenkeeperio but it must be fixed.

**Comment by rt2zz** [comment]
To clarify for others with this issue: If you have renamed your git repo (and consequently changed the remote uri), github will automatically redirect the old uri to the new uri so git keeps on working as expected. However it would appear `github-slug` does not follow the redirect hence the error when using greenkeeper. 

The solution (workaround?) is to point your github remote to the proper post name change uri.

**Comment by hemanth** [comment]
@rt2zz Either that or greenkeeper must also follow redirects.
