### ISSUE TITLE
npm package links to incorrect repo.

### ISSUE THREAD

**Issue by jdalton** [greenkeeperio/support#5]
I noticed the [npm package](https://www.npmjs.com/package/greenkeeper) links to the wrong repo.

**Comment by boennemann** [comment]
Hey @jdalton,

thanks for noticing. We're currently publishing the CLI from a private repo, but will make it public after one final clearance round. We'll correctly link it up to http://github.com/greenkeeper/greenkeeper very soon.

Best,
Stephan

**Comment by hemanth** [comment]
I came here to report the same. :+1:

**Comment by boennemann** [comment]
@jdalton @hemanth 

We've both made the repo public and added the Apache-2.0 license.
Thanks for your patience :+1:

**Comment by hemanth** [comment]
Sweet, thanks.
