### ISSUE TITLE
Customize commit message?

### ISSUE THREAD

**Issue by ariporad** [greenkeeperio/support#6]
Hi,

I love greenkeeper, but I do have one feature request: My repository uses the angular commit message rules, and this is enforced with a github status check. I would like to be able to customize the commit message that the bot uses, to be in line with those guidelines. Is this possible?

Thanks!

**Comment by janl** [comment]
Heya @ariporad,

thank you for the nice feedback, we’re glad you like Greenkeeper!

Customising commit messages is on our roadmap and not available yet, but you are in luck: we already use the Angular commit guidelines in our commits :)

Best
Jan
--

**Comment by ariporad** [comment]
Oops... Thanks! I really should have noticed that before. Sorry!

**Comment by janl** [comment]
no worries! :D

**Comment by ariporad** [comment]
@janl: I remember what I was missing. Your commit messages don't use the impressive tense, as the rules require. (I knew I couldn't possibly be that stupid!) Is it possible to change that?

Thanks!

**Comment by ariporad** [comment]
Ok, Thanks!


Ari

**Comment by boennemann** [comment]
This should be live now :)
