### ISSUE TITLE
Github SSL verification disabled.

### ISSUE THREAD

**Issue by ariporad** [greenkeeperio/support#7]
Ok, I have a real one this time.

Greenkeeper setup my repo so that SSL verification was disabled for the webhook: ![Screenshot](https://www.dropbox.com/s/v16lz5wrm6cepq9/Screenshot%202015-09-26%2013.31.19.png?dl=1)

I haven't yet tested if this can be re-enabled and have greenkeeper still work (I'm testing it right now). But regardless, it should not disable this by default.

Thanks, and once again I think greenkeeper is really awesome!

**Comment by ariporad** [comment]
Also, most webhooks are failing, due to service timeout:
![screenshot](https://www.dropbox.com/s/um06dvagy79hdwc/Screenshot%202015-09-26%2013.34.33.png?dl=1)

Is is perhaps that greenkeeper isn't setup for the status API webhook, but has accidentally been setup this way? (By default, it's setup to have the status and push permissions).

**Comment by christophwitzko** [comment]
Hi @ariporad,

both bugs should be resolved now. :relaxed: 
Thank you for catching them. :+1: 

have a great day,
Christoph
