### ISSUE TITLE
[FEATURE REQUEST] semver updates

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/support#8]
i don't like pinning dependencies, but i would still find this very helpful even if you included the semver ranges like `^` or `~` that were included before. ex. `"express": "^3.0.0"` would currently create a PR with `"express": "^4.13.3"`. any additional PR would still be helpful because updates tend to break and it busts `node_modules` caches

**Comment by gr2m** [comment]
Thanks for the suggestion, we are discussing it and will keep you posted!

**Comment by boennemann** [comment]
Hey @jonathanong,

we've just now deployed a bunch of feature that should make you really happy :)

1. We're now sending the PR with the existing version range. `1.0.0.` -> `1.0.1`, but `^1.0.0` -> `^1.0.1`
2. We're still creating branches for every new version, even if it's still covered by your range.
3. We're only opening PRs from these branches if your CI reports failure, if it passes we'll just remove them again.

Best,
Stephan

**Comment by jonathanong** [comment]
:+1:
